swagger: "2.0"
info:
  title: Meal optimization API
  version: "1.0"
  description: "Meal optimization using evolutionary algorithm API \n \n
  Made by Yarden Kantor and Noa Leron ©, 2023."
basePath: /
produces:
  - application/json
paths:
  /optimize:
    post:
      tags:
        - Optimize
      summary: Get the best optimize meal using evolutionary algorithm
      parameters:
        - in: formData
          name: fat
          type: number
          required: true
          description: fat importance in the meal
        - in: formData
          name: carbs
          type: number
          required: true
          description: carbs importance in the meal
        - in: formData
          name: protein
          type: number
          required: true
          description: protein importance in the meal
        - in: formData
          name: max_calories
          type: number
          required: true
          description: Maximum allowed calories in the meal
        - in: formData
          name: max_generation
          type: integer
          required: true
          description: Maximum allowed generations
      responses:
        200:
          description: A list of items that make up the best meal for the user based on the given constraints